### ISSUE TITLE
Remove preview icon

### ISSUE THREAD

**Issue by anitsirk** [MaharaProject/moodle-assignsubmission_mahara#23] opened 2016-10-27 18:32 UTC
The preview icon is not working (and hasn't for quite some time) due to stricter iframe rules in Mahara. It would be good to remove it so people don't wonder why it's not working. The page can still be looked at before submission by clicking on it.

**Comment by agwells** [comment] 2017-06-28 00:14
This is a duplicate of issue #7. :)

**Closed by agwells** 2017-06-28 00:14 UTC
Labels: duplicate
