### ISSUE TITLE
Using $this in static function

### ISSUE THREAD

**Issue by OlenaTatarintseva** [MaharaProject/moodle-assignsubmission_mahara#35] opened 2019-10-23 14:39 UTC
Hello,

I reviewed the plugin and it looks like there is the bug in the code. I noticed using $this in static function release_submitted_view() in mod/assign/submission/mahara/classes/observers.php. 

Best regards,
Olena Tatarintseva

**Comment by danmarsden** [comment] 2021-02-15 01:04
closing this as a duplicate of #33

**Closed by danmarsden** 2021-02-15 01:04 UTC
